# Generated by Django 5.2.1 on 2025-07-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_impuestoespecifico_productos_impuesto_especifico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impuestos_especificos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impuestos_especificos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='inventory.productos')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturascompras')),
            ],
        ),
    ]
