# Generated by Django 5.2.1 on 2025-06-30 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('rut_proveedor', models.CharField(help_text='Formato: XX.XXX.XXX-X', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('codigo_producto', models.CharField(default='00000000', max_length=50, unique=True)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('nombre_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.departamentos')),
                ('nombre_tipo', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.tiposproductos')),
                ('unidad_medida', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.unidadesmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_proveedor', to='inventory.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ultima_compra', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_info', to='inventory.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_info', to='inventory.proveedores')),
            ],
            options={
                'unique_together': {('producto', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id_receta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_ingrediente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_finales', to='inventory.productos')),
                ('id_producto_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_receta', to='inventory.productos')),
            ],
            options={
                'unique_together': {('id_producto_final', 'id_producto_ingrediente')},
            },
        ),
    ]
