# Generated by Django 5.2.1 on 2025-07-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpuestoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_impuesto', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='impuesto_especifico',
            field=models.ManyToManyField(blank=True, to='inventory.impuestoespecifico'),
        ),
        migrations.CreateModel(
            name='ProductoProveedorCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_proveedor', to='inventory.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_productos', to='inventory.proveedores')),
            ],
            options={
                'unique_together': {('producto', 'proveedor', 'codigo_proveedor')},
            },
        ),
    ]
